### PR TITLE
fix : utcToZonedTime returns next day when time matches offset

### LINKED ISSUE #38: utcToZonedTime returns next day when time matches offset
Hello, first of thanks for your work, dates are such a pain, I don't even want to think about working on a date library 😫

Anyway, I've come across this issue with date-fns-tz, I've tried to make a reduced issue here: https://codepen.io/atomcorp/pen/gObqoyX

In short the following returns a Date object for the **24th** not 23rd

```
utcToZonedTime(
  new Date('Thu Jan 23 2020 05:00:00 GMT+0000 (Greenwich Mean Time)'),
  'America/New_York' // -5 hours
);
````

It seems to happen when the inputted time matches the offset of the timezone. So if you move the time of the inputted date an hour back or forward, so it's different to the timezone offset, both utcToZonedTime and the native method return the same.

Like I said times are weird, so maybe this is expected behaviour!? 🤷‍♂️

### LINKED ISSUE #41: utcToZonedTime returns next day when time matches offset
From #38, which was prematurely closed by its author. Here I'm pasting and editing relevant parts from #38.

The issue appears to exist on Chrome versions 80 and above. Relevant Chrome bug report, which has been closed and marked as WON'T FIX: https://bugs.chromium.org/p/chromium/issues/detail?id=1045791

An example of the problem: https://codepen.io/atomcorp/pen/gObqoyX

In short the following returns a Date object for the 24th not 23rd:

```
utcToZonedTime(
  new Date('Thu Jan 23 2020 05:00:00 GMT+0000 (Greenwich Mean Time)'),
  'America/New_York' // -5 hours
);
```

It seems to happen when the inputted time matches the offset of the timezone. So if you move the time of the inputted date an hour back or forward, so it's different to the timezone offset, both utcToZonedTime and the native method return the same.

It's specifically related to do with Intl.DateTimeFormat which is used in tzTokenizeDate.

```
const dateTime = new Intl.DateTimeFormat('en-US', {
      hour12: false,
      timeZone: 'America/New_York',
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit'
    });

const date = dateTime.format(new Date(2020, 0, 25, 5, 0, 0));

// Chome 79/Firefox etc:  date === 01/25/2020, 00:00:00
// Chrome 81:  date === 01/25/2020, 24:00:00
```

Example: https://codepen.io/atomcorp/pen/bGNZzZz

### PR DESCRIPTION
**Pull request by hyyan**
fix #38 , fix #41

### CODE REVIEW

File: src/_lib/tzTokenizeDate/index.js [hunk 1]
```diff
@@ -43,16 +43,43 @@ function hackyOffset(dtf, date) {
...
       day: '2-digit',
       hour: '2-digit',
       minute: '2-digit',
-      second: '2-digit'
-    })
+      second: '2-digit',
+    });
+
+    var testDateTimeFormatted = testDateTime.format(new Date("2014-06-25T04:00:00.123Z"))
+    if(testDateTimeFormatted === '06/25/2014, 00:00:00' || testDateTimeFormatted === '‎06‎/‎25‎/‎2014‎ ‎00‎:‎00‎:‎00') {
```
Comment (marnusw) [inline src/_lib/tzTokenizeDate/index.js]: @hyyan it doesn't show here, but in my IDE I see strange characters before and after each part of the second date string you are comparing with. What character is this, and is it there intentionally?

I'm also curious why it is possible to have formatted output either with or without the comma? I would have expected only one possibility for a given locale.

File: src/_lib/tzTokenizeDate/index.js [hunk 2]
```diff
@@ -43,16 +43,43 @@ function hackyOffset(dtf, date) {
...
+      dtfCache[timeZone] = new Intl.DateTimeFormat('en-US', {
+        hour12: false,
```
Comment (marnusw) [inline src/_lib/tzTokenizeDate/index.js]: Do you know whether IE / Chrome <73 throws an error or warning when `hourCycle: undefined` is included? It would be nice to collapse this into a single object. `hour12` can be specified next to `hourCycle`, so we could have:

```js
hour12: false,
hourCycle: ... ? "h23" : undefined,
...
```

If you haven't looked at that and don't have the setup to test this easily I will merge it as is though.

Comment (hyyan) [reply src/_lib/tzTokenizeDate/index.js]: I did not really test it, but most likely it will do

File: src/_lib/tzTokenizeDate/index.js (hunk 1 above)
Comment (hyyan) [reply src/_lib/tzTokenizeDate/index.js]: I noticed when using the timezone polyfill for IE11, the date gets formatted without a comma, that's why I added the check, the string which contains hidden characters is copied directly from IE11 console
